rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
notifications:
  recipients:
    - memde@engineyard.com
  webhooks:
    urls:
      - https://ensemble.engineyard.com/travis
    on_success: always
    on_failure: always
    on_start: true
branches:
  only:
    - master
